language: java
sudo: false

script: ./mvnw clean verify -B
services:
  - mongodb

cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

after_success:
  - ./mvnw clean verify jacoco:report coveralls:report

branches:
  only:
  - master
