language: java
sudo: required

script:
  - ./mvnw clean verify -B
  - docker-compose up -d --build --force-recreate mongo
  - docker-compose up -d --build --force-recreate wcc-backend
  - sh verify_connectivity.sh

services:
  - mongodb
  - docker

cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

env:
  - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

after_success:
  - ./mvnw clean verify jacoco:report coveralls:report

branches:
  only:
  - master
