language: java
sudo: false

services:
  - mongodb

cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

after_success:
  - ./mvnw cobertura:cobertura coveralls:report

branches:
  only:
  - master
